/**
 * Example Risk Assessment Form Configuration
 * Demonstrates all field types and features
 */

import { FormConfig } from '../types/form';

export const sampleFormConfig: FormConfig = {
  id: 'vendor-risk-assessment',
  title: 'Vendor Risk Assessment Form',
  description: 'Please complete this comprehensive assessment to evaluate organizational risk across multiple dimensions.',
  maxRiskScore: 100,
  sections: [
    {
      id: 'compliance',
      title: 'Compliance & Certifications',
      description: 'Information about your certifications and compliance status',
      questions: [
        {
          id: 'soc2-cert',
          type: 'select',
          label: 'Do you have SOC2 certification?',
          options: [
            { label: 'Yes', value: 'yes', riskValue: 0 },
            { label: 'No', value: 'no', riskValue: 10 },
            { label: 'In Progress', value: 'in-progress', riskValue: 5 },
          ],
          required: true,
          riskWeight: 8,
          helpText: 'SOC2 certification is a significant security compliance benchmark',
          placeholder: 'Select an option',
        },
        {
          id: 'iso27001-cert',
          type: 'select',
          label: 'Do you have ISO 27001 certification?',
          options: ['Yes', 'No', 'In Progress'],
          required: true,
          riskWeight: 7,
          helpText: 'ISO 27001 is an international information security standard',
        },
        {
          id: 'compliance-certificate',
          type: 'file',
          label: 'Upload compliance certificate',
          accept: '.pdf',
          maxSize: 10,
          required: false,
          riskWeight: 3,
          helpText: 'Maximum file size is 10MB. PDF files only.',
          conditional: {
            questionId: 'soc2-cert',
            answer: 'yes',
          },
        },
      ],
    },
    {
      id: 'security',
      title: 'Security & Data Protection',
      description: 'Security practices and data protection measures',
      questions: [
        {
          id: 'data-encryption',
          type: 'checkbox',
          label: 'What encryption methods do you use? (Select all that apply)',
          options: [
            { label: 'End-to-end encryption', value: 'e2e', riskValue: 0 },
            { label: 'Encryption at rest', value: 'at-rest', riskValue: 2 },
            { label: 'Encryption in transit', value: 'in-transit', riskValue: 2 },
            { label: 'No encryption', value: 'none', riskValue: 10 },
          ],
          required: true,
          riskWeight: 9,
          helpText: 'Select all encryption methods you currently implement',
        },
        {
          id: 'data-breach-history',
          type: 'select',
          label: 'Have you had any data breaches in the past?',
          options: [
            { label: 'No', value: 'no', riskValue: 0 },
            { label: 'Yes, 1-2 incidents', value: 'minor', riskValue: 8 },
            { label: 'Yes, 3+ incidents', value: 'major', riskValue: 15 },
          ],
          required: true,
          riskWeight: 10,
        },
        {
          id: 'breach-explanation',
          type: 'text',
          label: 'Please explain the incidents',
          placeholder: 'Describe the nature and resolution of incidents',
          maxLength: 500,
          required: true,
          riskWeight: 3,
          conditional: {
            questionId: 'data-breach-history',
            answer: 'minor',
            operator: 'includes',
          },
        },
      ],
    },
    {
      id: 'financial',
      title: 'Financial & Operational',
      description: 'Financial stability and operational metrics',
      questions: [
        {
          id: 'annual-revenue',
          type: 'number',
          label: 'Annual Revenue (in millions USD)',
          placeholder: 'Enter amount',
          min: 0,
          max: 10000,
          step: 0.1,
          required: true,
          riskWeight: 6,
          helpText: 'Your annual revenue helps assess financial stability',
        },
        {
          id: 'employee-count',
          type: 'number',
          label: 'Number of Employees',
          placeholder: 'Enter count',
          min: 1,
          max: 100000,
          required: true,
          riskWeight: 4,
        },
        {
          id: 'years-in-business',
          type: 'number',
          label: 'Years in Business',
          placeholder: 'Enter years',
          min: 0,
          max: 200,
          required: true,
          riskWeight: 5,
        },
        {
          id: 'cybersecurity-insurance',
          type: 'select',
          label: 'Do you have cybersecurity insurance?',
          options: ['Yes', 'No', 'Unsure'],
          required: true,
          riskWeight: 7,
          helpText: 'Cybersecurity insurance provides financial protection',
        },
        {
          id: 'insurance-explanation',
          type: 'text',
          label: 'Why do you not have cybersecurity insurance?',
          placeholder: 'Explain your reason',
          maxLength: 300,
          required: true,
          riskWeight: 2,
          conditional: {
            questionId: 'cybersecurity-insurance',
            answer: 'No',
          },
        },
      ],
    },
    {
      id: 'operational',
      title: 'Operational Practices',
      description: 'Incident response and operational procedures',
      questions: [
        {
          id: 'incident-response-plan',
          type: 'select',
          label: 'Do you have a documented incident response plan?',
          options: [
            { label: 'Yes, comprehensive', value: 'comprehensive', riskValue: 0 },
            { label: 'Yes, basic', value: 'basic', riskValue: 3 },
            { label: 'No', value: 'no', riskValue: 8 },
          ],
          required: true,
          riskWeight: 8,
          helpText: 'A solid incident response plan is crucial for managing security events',
        },
        {
          id: 'compliance-training-date',
          type: 'date',
          label: 'When was your last security compliance training?',
          required: true,
          riskWeight: 5,
          helpText: 'Training should be conducted regularly',
        },
        {
          id: 'backup-strategy',
          type: 'checkbox',
          label: 'What backup and recovery strategies do you use? (Select all that apply)',
          options: [
            'Regular automated backups',
            'Off-site backup storage',
            'Redundant systems',
            'Regular recovery testing',
          ],
          required: true,
          riskWeight: 7,
          helpText: 'Multiple backup and recovery measures ensure business continuity',
        },
        {
          id: 'third-party-assessments',
          type: 'select',
          label: 'How often do you conduct third-party security assessments?',
          options: [
            { label: 'Quarterly or more', value: 'quarterly', riskValue: 0 },
            { label: 'Annually', value: 'annual', riskValue: 2 },
            { label: 'Every 2-3 years', value: 'multi-year', riskValue: 5 },
            { label: 'Never or unsure', value: 'never', riskValue: 10 },
          ],
          required: true,
          riskWeight: 7,
          helpText: 'Regular third-party assessments provide independent validation',
        },
      ],
    },
  ],
  submitText: 'Complete Assessment',
};
